### ISSUE TITLE
Implement function fx_conversion()

### ISSUE THREAD

**Issue by markusnam** [UBC-MDS/fxtracker#26]
write function code.

**Comment by markusnam** [comment]
I think you may make use of the parameter `interval = '1m'` when you call yf.download(). I tested this a bit. It seems that with `interval = '1m'`, you can get probably the latest price on yahoo.
e.g. yf.download('CADUSD=X', 'interval='1m')  <- i can see it updating every minute as of now.

**Comment by missarah96** [comment]
done
