### ISSUE TITLE
Write Function Docstring

### ISSUE THREAD

**Issue by THF-d8** [UBC-MDS/fxtracker#3]
(1) CCY pair, start date, end date - plot price graph
(2) CCY pair, target price - return the date if happened in the past
(3) CCY conversion
(4) CCY pair, start date, end date - plot P/L graph

**Comment by markusnam** [comment]
Done for fx_rate_lookup(). i.e. item 2

**Comment by markusnam** [comment]
@THF-d8 @missarah96
Suggest to add Authors and Date to your .py.
```
# Authors: Sarah Abdelazim, Markus Nam, Crystal Geng, Lennon Au-Yeung
# Date: Jan 13, 2023
```

**Comment by markusnam** [comment]
All done. Closing the issue.
