### ISSUE TITLE
Submit Milestone 1 on Canvas 

### ISSUE THREAD

**Issue by THF-d8** [UBC-MDS/fxtracker#6]
Needs to create a release and submit it to Canvas when we've finished everything required for Milestone 1

**Comment by markusnam** [comment]
Reminder:
Team work contract should be submitted separately (should not be uploaded to the public repo).
Quote from submission instructions
> A link to your team work document that is accessible to the teaching team. Alternatively a copy of your team work document can be pasted there.

**Comment by markusnam** [comment]
Submission done. Closing the issue.
