### ISSUE TITLE
Milestone 2 Feedback

### ISSUE THREAD

**Issue by negsadr** [UBC-MDS/fxtracker#73]
> **Congratulations on finishing milestone 2!** We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.  
> We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
> If anything is unclear, please feel free to ask questions in this issue thread.

---

## 1. Write test cases and code iteratively
rubric={accuracy:20,quality:10,mechanics:10}

- [ ] The documentation for one of the test functions is missing. - **quality -2**

#### 1. Create project structure for the R project
rubric={mechanics:20}

Well done!

## 3. R package function specifications
rubric={quality:10}

Well done!

## 4. Specific expectations for this milestone are:
rubric={mechanics:10}

Well done!

## 5. Submission instructions
rubric={mechanics:10}

Well done!

**Comment by markusnam** [comment]
Hello,
Re (3), would you let us know which documentation is it? In the roxygen comments, we have examples for each function.
Re (5), we have a project board. You may find it here https://github.com/orgs/UBC-MDS/projects/34. You may check, for example, the issue with the tag `R`.

**Comment by markusnam** [comment]
Thanks. After consulting Florencia, we are going to leave it as it is.
Closing this issue.
